package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Clinica generated by hbm2java
 */
public class Clinica  implements java.io.Serializable {


     private BigDecimal idclinica;
     private Departamento departamento;
     private Municipio municipio;
     private String nombre;
     private String direccion;
     private Set medicos = new HashSet(0);
     private Set consultas = new HashSet(0);

    public Clinica() {
    }

	
    public Clinica(BigDecimal idclinica, Departamento departamento, Municipio municipio, String nombre, String direccion) {
        this.idclinica = idclinica;
        this.departamento = departamento;
        this.municipio = municipio;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Clinica(BigDecimal idclinica, Departamento departamento, Municipio municipio, String nombre, String direccion, Set medicos, Set consultas) {
       this.idclinica = idclinica;
       this.departamento = departamento;
       this.municipio = municipio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.medicos = medicos;
       this.consultas = consultas;
    }
   
    public BigDecimal getIdclinica() {
        return this.idclinica;
    }
    
    public void setIdclinica(BigDecimal idclinica) {
        this.idclinica = idclinica;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getMedicos() {
        return this.medicos;
    }
    
    public void setMedicos(Set medicos) {
        this.medicos = medicos;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


