package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private BigDecimal idconsulta;
     private Medico medico;
     private Paciente paciente;
     private Clinica clinica;
     private Examen examen;
     private Signosvitales signosvitales;
     private BigDecimal estadoconsulta;
     private Date fecha;
     private String sintomas;
     private String diagnostico;
     private String tratamiento;
     private String medicamentos;

    public Consulta() {
    }

	
    public Consulta(BigDecimal idconsulta, Medico medico, Paciente paciente, Clinica clinica, Signosvitales signosvitales, BigDecimal estadoconsulta, Date fecha, String sintomas, String diagnostico) {
        this.idconsulta = idconsulta;
        this.medico = medico;
        this.paciente = paciente;
        this.clinica = clinica;
        this.signosvitales = signosvitales;
        this.estadoconsulta = estadoconsulta;
        this.fecha = fecha;
        this.sintomas = sintomas;
        this.diagnostico = diagnostico;
    }
    public Consulta(BigDecimal idconsulta, Medico medico, Paciente paciente, Clinica clinica, Examen examen, Signosvitales signosvitales, BigDecimal estadoconsulta, Date fecha, String sintomas, String diagnostico, String tratamiento, String medicamentos) {
       this.idconsulta = idconsulta;
       this.medico = medico;
       this.paciente = paciente;
       this.clinica = clinica;
       this.examen = examen;
       this.signosvitales = signosvitales;
       this.estadoconsulta = estadoconsulta;
       this.fecha = fecha;
       this.sintomas = sintomas;
       this.diagnostico = diagnostico;
       this.tratamiento = tratamiento;
       this.medicamentos = medicamentos;
    }
   
    public BigDecimal getIdconsulta() {
        return this.idconsulta;
    }
    
    public void setIdconsulta(BigDecimal idconsulta) {
        this.idconsulta = idconsulta;
    }
    public Medico getMedico() {
        return this.medico;
    }
    
    public void setMedico(Medico medico) {
        this.medico = medico;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }
    public Examen getExamen() {
        return this.examen;
    }
    
    public void setExamen(Examen examen) {
        this.examen = examen;
    }
    public Signosvitales getSignosvitales() {
        return this.signosvitales;
    }
    
    public void setSignosvitales(Signosvitales signosvitales) {
        this.signosvitales = signosvitales;
    }
    public BigDecimal getEstadoconsulta() {
        return this.estadoconsulta;
    }
    
    public void setEstadoconsulta(BigDecimal estadoconsulta) {
        this.estadoconsulta = estadoconsulta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getSintomas() {
        return this.sintomas;
    }
    
    public void setSintomas(String sintomas) {
        this.sintomas = sintomas;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public String getMedicamentos() {
        return this.medicamentos;
    }
    
    public void setMedicamentos(String medicamentos) {
        this.medicamentos = medicamentos;
    }




}


