package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private BigDecimal idempleado;

    public Empleados() {
    }

    public Empleados(BigDecimal idempleado) {
       this.idempleado = idempleado;
    }
   
    public BigDecimal getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(BigDecimal idempleado) {
        this.idempleado = idempleado;
    }




}


