package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Examen generated by hbm2java
 */
public class Examen  implements java.io.Serializable {


     private BigDecimal idexamen;
     private Set consultas = new HashSet(0);

    public Examen() {
    }

	
    public Examen(BigDecimal idexamen) {
        this.idexamen = idexamen;
    }
    public Examen(BigDecimal idexamen, Set consultas) {
       this.idexamen = idexamen;
       this.consultas = consultas;
    }
   
    public BigDecimal getIdexamen() {
        return this.idexamen;
    }
    
    public void setIdexamen(BigDecimal idexamen) {
        this.idexamen = idexamen;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


