package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Medico generated by hbm2java
 */
public class Medico  implements java.io.Serializable {


     private BigDecimal idmedico;
     private Clinica clinica;
     private String nombre;
     private String apellidos;
     private String especialidad;
     private Set consultas = new HashSet(0);

    public Medico() {
    }

	
    public Medico(BigDecimal idmedico, Clinica clinica, String nombre, String apellidos, String especialidad) {
        this.idmedico = idmedico;
        this.clinica = clinica;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.especialidad = especialidad;
    }
    public Medico(BigDecimal idmedico, Clinica clinica, String nombre, String apellidos, String especialidad, Set consultas) {
       this.idmedico = idmedico;
       this.clinica = clinica;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.especialidad = especialidad;
       this.consultas = consultas;
    }
   
    public BigDecimal getIdmedico() {
        return this.idmedico;
    }
    
    public void setIdmedico(BigDecimal idmedico) {
        this.idmedico = idmedico;
    }
    public Clinica getClinica() {
        return this.clinica;
    }
    
    public void setClinica(Clinica clinica) {
        this.clinica = clinica;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getEspecialidad() {
        return this.especialidad;
    }
    
    public void setEspecialidad(String especialidad) {
        this.especialidad = especialidad;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


