package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private BigDecimal idmunicipio;
     private Departamento departamento;
     private String nombre;
     private Set clinicas = new HashSet(0);
     private Set pacientes = new HashSet(0);

    public Municipio() {
    }

    public Municipio(Departamento departamento, String nombre) {
        this.departamento = departamento;
        this.nombre = nombre;
    }

    
    
    public Municipio(BigDecimal idmunicipio, Departamento departamento, String nombre) {
        this.idmunicipio = idmunicipio;
        this.departamento = departamento;
        this.nombre = nombre;
    }
    public Municipio(BigDecimal idmunicipio, Departamento departamento, String nombre, Set clinicas, Set pacientes) {
       this.idmunicipio = idmunicipio;
       this.departamento = departamento;
       this.nombre = nombre;
       this.clinicas = clinicas;
       this.pacientes = pacientes;
    }
   
    public BigDecimal getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(BigDecimal idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getClinicas() {
        return this.clinicas;
    }
    
    public void setClinicas(Set clinicas) {
        this.clinicas = clinicas;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


