package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private BigDecimal idpaciente;
     private Departamento departamento;
     private Municipio municipio;
     private String nombre;
     private String apellidos;
     private Date fechanacimiento;
     private String profesion;
     private String dui;
     private String nombremadre;
     private String apellidomadre;
     private String nombrepadre;
     private String apellidopadre;
     private String conyugue;
     private String estadocivil;
     private String genero;
     private String direccion;
     private Set consultas = new HashSet(0);

    public Paciente() {
    }

    public Paciente(Departamento departamento, Municipio municipio, String nombre, String apellidos, Date fechanacimiento, String profesion, String dui, String nombremadre, String apellidomadre, String nombrepadre, String apellidopadre, String conyugue, String estadocivil, String genero, String direccion) {
       
        this.departamento = departamento;
        this.municipio = municipio;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechanacimiento = fechanacimiento;
        this.profesion = profesion;
        this.dui = dui;
        this.nombremadre = nombremadre;
        this.apellidomadre = apellidomadre;
        this.nombrepadre = nombrepadre;
        this.apellidopadre = apellidopadre;
        this.conyugue = conyugue;
        this.estadocivil = estadocivil;
        this.genero = genero;
        this.direccion = direccion;
    }

	
    
    
    public Paciente(BigDecimal idpaciente, Departamento departamento, Municipio municipio, String nombre, String apellidos, Date fechanacimiento, String dui, String estadocivil, String genero) {
        this.idpaciente = idpaciente;
        this.departamento = departamento;
        this.municipio = municipio;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.fechanacimiento = fechanacimiento;
        this.dui = dui;
        this.estadocivil = estadocivil;
        this.genero = genero;
    }
    public Paciente(BigDecimal idpaciente, Departamento departamento, Municipio municipio, String nombre, String apellidos, Date fechanacimiento, String profesion, String dui, String nombremadre, String apellidomadre, String nombrepadre, String apellidopadre, String conyugue, String estadocivil, String genero, String direccion, Set consultas) {
       this.idpaciente = idpaciente;
       this.departamento = departamento;
       this.municipio = municipio;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.fechanacimiento = fechanacimiento;
       this.profesion = profesion;
       this.dui = dui;
       this.nombremadre = nombremadre;
       this.apellidomadre = apellidomadre;
       this.nombrepadre = nombrepadre;
       this.apellidopadre = apellidopadre;
       this.conyugue = conyugue;
       this.estadocivil = estadocivil;
       this.genero = genero;
       this.direccion = direccion;
       this.consultas = consultas;
    }
   
    public BigDecimal getIdpaciente() {
        return this.idpaciente;
    }
    
    public void setIdpaciente(BigDecimal idpaciente) {
        this.idpaciente = idpaciente;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Municipio getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Municipio municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getProfesion() {
        return this.profesion;
    }
    
    public void setProfesion(String profesion) {
        this.profesion = profesion;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNombremadre() {
        return this.nombremadre;
    }
    
    public void setNombremadre(String nombremadre) {
        this.nombremadre = nombremadre;
    }
    public String getApellidomadre() {
        return this.apellidomadre;
    }
    
    public void setApellidomadre(String apellidomadre) {
        this.apellidomadre = apellidomadre;
    }
    public String getNombrepadre() {
        return this.nombrepadre;
    }
    
    public void setNombrepadre(String nombrepadre) {
        this.nombrepadre = nombrepadre;
    }
    public String getApellidopadre() {
        return this.apellidopadre;
    }
    
    public void setApellidopadre(String apellidopadre) {
        this.apellidopadre = apellidopadre;
    }
    public String getConyugue() {
        return this.conyugue;
    }
    
    public void setConyugue(String conyugue) {
        this.conyugue = conyugue;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


