package Modelo;
// Generated Oct 11, 2017 12:04:57 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Signosvitales generated by hbm2java
 */
public class Signosvitales  implements java.io.Serializable {


     private BigDecimal idsignosvitales;
     private String temperatura;
     private String peso;
     private String altura;
     private String presionarterial;
     private String pulsocardiaco;
     private Set consultas = new HashSet(0);

    public Signosvitales() {
    }

	
    public Signosvitales(BigDecimal idsignosvitales, String temperatura, String peso, String altura, String presionarterial, String pulsocardiaco) {
        this.idsignosvitales = idsignosvitales;
        this.temperatura = temperatura;
        this.peso = peso;
        this.altura = altura;
        this.presionarterial = presionarterial;
        this.pulsocardiaco = pulsocardiaco;
    }
    public Signosvitales(BigDecimal idsignosvitales, String temperatura, String peso, String altura, String presionarterial, String pulsocardiaco, Set consultas) {
       this.idsignosvitales = idsignosvitales;
       this.temperatura = temperatura;
       this.peso = peso;
       this.altura = altura;
       this.presionarterial = presionarterial;
       this.pulsocardiaco = pulsocardiaco;
       this.consultas = consultas;
    }
   
    public BigDecimal getIdsignosvitales() {
        return this.idsignosvitales;
    }
    
    public void setIdsignosvitales(BigDecimal idsignosvitales) {
        this.idsignosvitales = idsignosvitales;
    }
    public String getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(String temperatura) {
        this.temperatura = temperatura;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getAltura() {
        return this.altura;
    }
    
    public void setAltura(String altura) {
        this.altura = altura;
    }
    public String getPresionarterial() {
        return this.presionarterial;
    }
    
    public void setPresionarterial(String presionarterial) {
        this.presionarterial = presionarterial;
    }
    public String getPulsocardiaco() {
        return this.pulsocardiaco;
    }
    
    public void setPulsocardiaco(String pulsocardiaco) {
        this.pulsocardiaco = pulsocardiaco;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


