DROP SEQUENCE HR.MED_SEQ;/  
DROP SEQUENCE HR.PAC_SEQ;/
DROP SEQUENCE HR.CLI_SEQ;/
DROP SEQUENCE HR.EXA_SEQ;/
DROP SEQUENCE HR.CON_SEQ;/
DROP SEQUENCE HR.SIG_SEQ;/
DROP SEQUENCE HR.MUN_SEQ;/
DROP SEQUENCE HR.DEP_SEQ;/
DROP SEQUENCE HR.EMP_SEQ;/

DROP table HR.CONSULTA CASCADE CONSTRAINTS;/
DROP table HR.CLINICA CASCADE CONSTRAINTS;/
DROP table HR.MEDICO CASCADE CONSTRAINTS;/
DROP table HR.EXAMEN CASCADE CONSTRAINTS;/
DROP table HR.PACIENTE CASCADE CONSTRAINTS;/
DROP table HR.EMPLEADOS CASCADE CONSTRAINTS;/
DROP table HR.SIGNOSVITALES CASCADE CONSTRAINTS;/
DROP table HR.DEPARTAMENTO CASCADE CONSTRAINTS;/
DROP table HR.MUNICIPIO CASCADE CONSTRAINTS;/



/*==============================================================*/
/* Table: MEDICO                                                */
/*==============================================================*/

create table HR.MEDICO 
(
   IDMEDICO       INTEGER              not null,
   NOMBRE         VARCHAR2(25)         not null,
   APELLIDOS      VARCHAR2(25)         not null,
   ESPECIALIDAD   VARCHAR2(25)         not null,
   IDCLINICA      INTEGER              not null,
   
   constraint PK_MEDICO primary key (IDMEDICO)
);
/*==============================================================*/
/* Table: PACIENTE                                              */
/*==============================================================*/
create table HR.PACIENTE 
(
   IDPACIENTE           INTEGER              not null,
   NOMBRE               VARCHAR2(25)         not null,
   APELLIDOS            VARCHAR2(25)         not null,
   FECHANACIMIENTO      DATE                 not null,
   PROFESION            VARCHAR2(25),         
   DUI                  VARCHAR2(25)         not null,
   NOMBREMADRE          VARCHAR2(50),
   APELLIDOMADRE        VARCHAR2(50),
   NOMBREPADRE          VARCHAR2(25),
   APELLIDOPADRE        VARCHAR2(25),
   CONYUGUE             VARCHAR2(50),
   ESTADOCIVIL          VARCHAR2(25)         not null,
   GENERO               VARCHAR2(25)         not null,
   DIRECCION           VARCHAR2(75),
   IDDEPARTAMENTO       INTEGER              not null,
   IDMUNICIPIO          INTEGER              not null,

   constraint PK_PACIENTE primary key (IDPACIENTE)
);
/*==============================================================*/
/* Table: CLINICA                                               */
/*==============================================================*/
create table HR.CLINICA 
(
    IDCLINICA           INTEGER             not null,
    NOMBRE              VARCHAR2(50)        not null,
    DIRECCION           VARCHAR2(75)        not null,
    IDDEPARTAMENTO      INTEGER             not null,
    IDMUNICIPIO         INTEGER             not null,

    constraint PK_CLINICA primary key (IDCLINICA)
);
/*==============================================================*/
/* Table: EXAMEN                                              */
/*==============================================================*/
create table HR.EXAMEN 
(
    IDEXAMEN    INTEGER             not null,
    IDCONSULTA           INTEGER              not null,
    /* Faltan campos de examenes*/

    constraint PK_EXAMEN primary key (IDEXAMEN)
);
/*==============================================================*/
/* Table: CONSULTA                                              */
/*==============================================================*/
create table HR.CONSULTA 
(
   IDCONSULTA           INTEGER              not null,
   IDMEDICO             INTEGER              not null,
   IDPACIENTE           INTEGER              not null,
   ESTADOCONSULTA       SMALLINT             not null,
   IDCLINICA            INTEGER              not null,  
   FECHA                DATE                 not null,
   SINTOMAS             VARCHAR2(200),
   DIAGNOSTICO          VARCHAR2(200),
   TRATAMIENTO          VARCHAR2(150),
   MEDICAMENTOS         VARCHAR2(150),

   constraint PK_CONSULTA primary key (IDCONSULTA)
);

/*==============================================================*/
/* Table: SIGNOSVITALES                                         */
/*==============================================================*/
create table HR.SIGNOSVITALES 
(
    IDSIGNOSVITALES      INTEGER              not null,
    IDCONSULTA           INTEGER              not null,
    TEMPERATURA          VARCHAR2(5)          not null,
    PESO                 VARCHAR2(5)          not null,
    ALTURA               VARCHAR2(5)          not null,
    PRESIONARTERIAL      VARCHAR2(5)          not null,
    PULSOCARDIACO        VARCHAR2(5)          not null,

    constraint PK_SIGNOSVITALES primary key (IDSIGNOSVITALES)
);

/*==============================================================*/
/* Table: DEPARTAMENTO                                          */
/*==============================================================*/
create table HR.DEPARTAMENTO 
(
   IDDEPARTAMENTO   INTEGER              not null,
   NOMBRE           VARCHAR2(25)         not null,
  
   constraint PK_DEPARTAMENTO primary key (IDDEPARTAMENTO)
);

/*==============================================================*/
/* Table: MUNICIPIO                                             */
/*==============================================================*/
create table HR.MUNICIPIO 
(
   IDMUNICIPIO          INTEGER              not null,
   NOMBRE               VARCHAR2(30)         not null,
   IDDEPARTAMENTO       INTEGER              not null,

   constraint PK_MUNICIPIO primary key (IDMUNICIPIO)
);
/*==============================================================*/
/* Table: EMPLEADOS                                             */
/*==============================================================*/
create table HR.EMPLEADOS (
    IDEMPLEADO    INTEGER             not null,
    /* Faltan campos de EMPLEADOS*/

    constraint PK_EMPLEADO primary key (IDEMPLEADO)
);

/*==============================================================*/
/* Table: RELACIONES                                            */
/*==============================================================*/
/*RELACION TABLA MUNICIPIO-DEPARTAMENTO*/
alter table HR.MUNICIPIO
   add constraint FK_MUNICIPIO_DEPARTAMENTO foreign key (IDDEPARTAMENTO)
      references HR.DEPARTAMENTO (IDDEPARTAMENTO);

/*RELACION TABLA CLINICA*/
alter table HR.CLINICA
   add constraint FK_CLINICA_DEPARTAMENTO foreign key (IDDEPARTAMENTO)
      references HR.DEPARTAMENTO (IDDEPARTAMENTO);


alter table HR.CLINICA
   add constraint FK_CLINICA_MUNICIPIO foreign key (IDMUNICIPIO)
      references HR.MUNICIPIO (IDMUNICIPIO);

/*RELACION TABLA PACIENTE*/
alter table HR.PACIENTE
   add constraint FK_PACIENTE_MUNICIPIO foreign key (IDMUNICIPIO)
      references HR.MUNICIPIO (IDMUNICIPIO);

alter table HR.PACIENTE
   add constraint FK_PACIENTE_DEPARTAMENTO foreign key (IDDEPARTAMENTO)
      references HR.DEPARTAMENTO (IDDEPARTAMENTO);

/*RELACION TABLA CONSULTAS*/
alter table HR.CONSULTA
   add constraint FK_CONSULTA_CLINICA foreign key (IDCLINICA)
      references HR.CLINICA (IDCLINICA);

alter table HR.CONSULTA
   add constraint FK_CONSULTA_PACIENTE foreign key (IDPACIENTE)
      references HR.PACIENTE (IDPACIENTE);

alter table HR.CONSULTA
   add constraint FK_CONSULTA_MEDICO foreign key (IDMEDICO)
      references HR.MEDICO (IDMEDICO);
      
/*RELACION TABLA EXAMEN*/
alter table HR.EXAMEN
   add constraint FK_EXAMEN_CONSULTA foreign key (IDCONSULTA)
      references HR.CONSULTA (IDCONSULTA);

/*RELACION TABLA SIGNOSVITALES*/
alter table HR.SIGNOSVITALES
   add constraint FK_SIGNOSVITALES_CONSULTA foreign key (IDCONSULTA)
      references HR.CONSULTA(IDCONSULTA);

/*RELACION TABLA MEDICO*/
alter table HR.MEDICO
   add constraint FK_MEDICO_CLINICA foreign key (IDCLINICA)
      references HR.CLINICA (IDCLINICA);

/*==============================================================*/
/* PROGRAMACION                                                 */
/*==============================================================*/

CREATE SEQUENCE HR.MED_SEQ START WITH 1 INCREMENT BY 1;  
CREATE SEQUENCE HR.PAC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.CLI_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.EXA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.CON_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.SIG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.MUN_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.DEP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HR.EMP_SEQ START WITH 1 INCREMENT BY 1;/


CREATE OR REPLACE TRIGGER HR.MED_BIR 
BEFORE INSERT ON HR.MEDICO 
FOR EACH ROW 
BEGIN 
    SELECT MED_SEQ.NEXTVAL INTO :new.IDMEDICO FROM dual;
END;
/

CREATE OR REPLACE TRIGGER HR.PAC_BIR 
BEFORE INSERT ON HR.PACIENTE 
FOR EACH ROW 
BEGIN 
    SELECT PAC_SEQ.NEXTVAL INTO :new.IDPACIENTE FROM dual;
END;
/

CREATE OR REPLACE TRIGGER HR.CLI_BIR 
BEFORE INSERT ON HR.CLINICA 
FOR EACH ROW 
BEGIN 
    SELECT HR.CLI_SEQ.NEXTVAL INTO :new.IDCLINICA  FROM dual;
END;
/

CREATE OR REPLACE TRIGGER HR.EXA_BIR 
BEFORE INSERT ON HR.EXAMEN
FOR EACH ROW 
BEGIN 
    SELECT EXA_SEQ.NEXTVAL
    INTO :new.IDEXAMEN
    FROM dual;
END;
/
CREATE OR REPLACE TRIGGER HR.CON_BIR 
BEFORE INSERT ON HR.CONSULTA
FOR EACH ROW 
BEGIN 
    SELECT CON_SEQ.NEXTVAL
    INTO :new.IDCONSULTA
    FROM dual;
END; 
/

CREATE OR REPLACE TRIGGER HR.SIG_BIR 
BEFORE INSERT ON HR.SIGNOSVITALES
FOR EACH ROW 
BEGIN 
    SELECT SIG_SEQ.NEXTVAL
    INTO :new.IDSIGNOSVITALES
    FROM dual;
END;
/
 
CREATE OR REPLACE TRIGGER HR.DEP_BIR 
BEFORE INSERT ON HR.DEPARTAMENTO
FOR EACH ROW 
BEGIN 
    SELECT DEP_SEQ.NEXTVAL
    INTO :new.IDDEPARTAMENTO
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER HR.MUN_BIR 
BEFORE INSERT ON HR.MUNICIPIO
FOR EACH ROW 
BEGIN 
    SELECT MUN_SEQ.NEXTVAL
    INTO :new.IDMUNICIPIO
    FROM dual;
END;
/

CREATE OR REPLACE TRIGGER HR.EMP_BIR 
BEFORE INSERT ON HR.EMPLEADOS
FOR EACH ROW 
BEGIN 
    SELECT EMP_SEQ.NEXTVAL
    INTO :new.IDEMPLEADO
    FROM dual;
END;
/


/*==============================================================*/
/*   DATOS DEPARTAMENTO                                         */
/*==============================================================*/

INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Ahuachapan');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Cabañas');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Chalatenango');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Cuscatlan');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('La Libertad');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('La Paz');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('La Union');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Morazan');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('San Miguel');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('San Salvador');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('San Vicente');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Santa Ana');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Sonsonate');
INSERT INTO HR.DEPARTAMENTO (NOMBRE) VALUES ('Usulutan');


INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ahuachapan', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Apaneca', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Atiquizaya', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Concepcion de Ataco', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Refugio', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Guaymango', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jujutla', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Menendez', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Lorenzo', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Pedro Puxtla', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('AhuachapanTacuba', 1);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Turin', 1);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sensuntepeque', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cinquera', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Dolores', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Guacotetecti', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ilobasco', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jutiapa', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Isidro', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tejutepeque', 2);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Victoria', 2);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chalatenango', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Agua Caliente', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Arcatao', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Azacualpa', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cancasque', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Citala', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Comalapa', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Concepcion Quezaltepeque', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Dulce Nombre de Maria', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Carrizal', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Paraiso', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('La Laguna', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('La Palma', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('La Reina', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Las Flores', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Las Vueltas', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nombre de Jesus', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Concepcion', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Trinidad', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ojos de Agua', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Potonico', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio de la Cruz', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio de los Ranchos', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Fernando', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Lempa', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Morazan', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Ignacio', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Isidro Labrador', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Luis del Carmen', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Miguel de Mercedes', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Rafael', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Rita', 3);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tejutla', 3);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cojutepeque', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Candelaria', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Carmen', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('EL Rosario', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Monte San Juan', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Oratorio de Concepcion', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Bartolome Perulapia', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Cristobal', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Jose Guayabal', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Pedro Perulan', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Rafael Cedros', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Ramon', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Cruz Analquito', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Cruz Michapa', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Suchitoto', 4);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tenancingo', 4);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Tecla', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Antiguo Cuscatlan', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chilitiupan', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ciudad Arce', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Colon', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Comasagua', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Huizucar', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jayaque', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jicalapa', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('La Libertad', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nuevo Cuzcatlan', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Quezaltepeque', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Juan Opico', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sacacoyo', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Jose Villanueva', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Matias', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Pablo Tacachico', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Talnique', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tamanique', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Teotepeque', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tepecoyo', 5);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Zaragoza', 5);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Zacatecoluca', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cuyultitan', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Rosario', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jerusalen', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Mercedes La Ceiba', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Olocuilta', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Paraiso de Osorio', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio Masahuat', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Emigdio', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Chinameca', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Pedro Masahuat', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Juan Nonualco', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Juan Talpa', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Juan Tepezontes', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Luis La Herradura', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Luis Talpa', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Miguel Tepezontes', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Pedro Nonualco', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Rafael Obrajuelo', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Maria Ostuma', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santiago Nonualco', 6);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tapalhuaca', 6);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('La Union', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Anamoros', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Bolivar', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Concepcion de Oriente', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Conchagua', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Carmen', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Sauce', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Itipuca', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Lislique', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Meanguera del Golfo', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Esparta', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Pasaquina', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Poloros', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Alejo', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Jose', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Rosa de Lima', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Yayantique', 7);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Yucuaiquin', 7);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Gotera', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Arambala', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cacaopera', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chilanga', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cotintios', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Delicias de Concepcion', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('EL Divisadero', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Rosario', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Gualococti', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Guatajiagua', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Joateca', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jocoaitique', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jocoro', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Lolotiquillo', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Meanguera', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Osicala', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Perquin', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Carlos', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Fernando', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Isidro', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Simon', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sensembra', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sociedad', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Torola', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Yamabal', 8);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Yoloaiquin', 8);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Miguel', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Carolina', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chapeltique', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chinameca', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chirilagua', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ciudad Barrios', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Comacaran', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Transito', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Lolotique', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Moncagua', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Guadalupe', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nuevo Eden de San Juan', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Quelepa', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Gerardo', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Jorge', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Luis de la Reina', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Rafael Oriente', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sesori', 9);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Uluazapa', 9);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Salvador', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Aguilares', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Apopa', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ayutuxtepeque', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cuscatancingo', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Delgado', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Paisnal', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Guazapa', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ilopango', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Mejicanos', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nejapa', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Panchimalco', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Rosario de Mora', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Marcos', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Martin', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santiago Texacuangos', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santo Tomas', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Soyapango', 10);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tonacatepeque', 10);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Vicente', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Apastepeque', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Guadalupe', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Cayetano Istepeque', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Esteban Catarina', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Ildefonso', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Lorenzo', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Sebastian', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Clara', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santo Domingo', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tecoluca', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tepetitan', 11);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Verapaz', 11);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Ana', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Candelaria de la Frontera', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Chalchuapa', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Coatepeque', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Congo', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Porvenir', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Masahuat', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Metapan', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio Pajonal', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Sebastian Salitrillo', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Rosa Guachipilin', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santiago de la Frontera', 12);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Texistepeque', 12);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sonsonate', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Acajutla', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Armenia', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Caluco', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Cuisnahuat', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Izalco', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Juayua', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nahuizalco', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nahulingo', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Salcoatitan', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Antonio del Monte', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Julian', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Catarina Masahuat', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Isabel Ishuatan', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santo Domingo de Guzman', 13);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Sonzacate', 13);

INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Usulutan', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Alegria', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Berlin', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('California', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Concepcion Batres', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Triunfo', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ereguayquin', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Estanzuelas', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jiquilisco', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jucuapa', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jucuaran', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Mercedes Umana', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Granada', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ozatlan', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Puerto El Triunfo', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Agustin', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Buenaventura', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Dionisio', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Javier', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Elena', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Maria', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santiago de Maria', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tecapan', 14);

SELECT * FROM MUNICIPIO;
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Concepcion Batres', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('El Triunfo', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ereguayquin', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Estanzuelas', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jiquilisco', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jucuapa', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Jucuaran', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Mercedes Umana', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Nueva Granada', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Ozatlan', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Puerto El Triunfo', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Agustin', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Buenaventura', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Dionisio', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('San Francisco Javier', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Elena', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santa Maria', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Santiago de Maria', 14);
INSERT INTO HR.MUNICIPIO (NOMBRE, IDDEPARTAMENTO) VALUES ('Tecapan', 14);

